% Packet preparation
clc
clear
close all

% The following lines recreate the payload that is transmitted
% An image is transformed in a binary file
fileTx = 'capra.jpg';                             % Image file name
scale = 1;                                          % Image scaling factor
% Import the specified image file and covert it to a binary stream.

fData = imread(fileTx);                                                 % Read image data from file
origSize = size(fData);                                                 % Original input image size
scaledSize = max(floor(scale.*origSize(1:2)),1);                        % Calculate new image size
heightIx = min(round(((1:scaledSize(1))-0.5)./scale+0.5),origSize(1));
widthIx = min(round(((1:scaledSize(2))-0.5)./scale+0.5),origSize(2));
fData = fData(heightIx,widthIx,:);                                      % Resize image
imsize = size(fData);                                                   % Store new image size
binData = dec2bin(fData(:),8);                                          % Convert to 8 bit unsigned binary
trData = reshape((binData-'0').',1,[]).';                               % Create binary stream

% Preamble generaltio
barker = comm.BarkerCode("Length",13,SamplesPerFrame=13);
preamble = (1+barker())/2;  % Length 13, unipolar
preamble = [preamble;preamble];

msgLen = length(trData);
frameLen = 10000;
numFrames = ceil(msgLen/frameLen);

data = zeros(msgLen+length(preamble)*numFrames+16*numFrames, 1);
numLen = 16;  % 2 bytes to send the number of the packet
tot_packet = frameLen+length(preamble)+numLen; % total length of the packet

% The transmitted file is generated by the for loop, a preamble is followed
% by the packet number and by a payload of 10 000 bits
for idx = 1 : numFrames
    idx_bin = dec2bin(idx,16);
    idx_bin = reshape((idx_bin-'0').',1,[]).';
    if idx == 1
        payload = trData(1:(frameLen));
        data(1:tot_packet) = [preamble', idx_bin', payload'];
        fprintf("Packet %d\n",idx)
    else
        if (frameLen*(idx))> msgLen
            payload = trData(((idx-1)*(frameLen)+1):end);
            data(((idx-1)*tot_packet+1):end) = [preamble', idx_bin', payload'];
            fprintf("Packet %d\n",idx)
        else
            payload = trData(((idx-1)*(frameLen)+1):(frameLen*idx));
            data(((idx-1)*tot_packet+1):tot_packet*idx) = [preamble', idx_bin', payload'];
            fprintf("Packet %d\n",idx)
        end
    end
end

% A long preamble is added before the all file
len_prepre=50000;
first_preamble_bin = zeros(1,len_prepre);

for k =1:len_prepre
    if mod(k,2)== 0
        first_preamble_bin(k) = dec2bin(1,1);
    else
        first_preamble_bin(k) = dec2bin(0,1);
    end
end

first_preamble = reshape((first_preamble_bin-'0').',1,[]).';
data = [first_preamble;data];

% The data to transmit are saved in bin file
fid = fopen('transmitted.bin', 'wt');
fwrite(fid, data);
fclose(fid);